### ISSUE TITLE
setMaxHeight does not work as expected

### ISSUE THREAD

**Issue by voodoohoo** [vaadin-component-factory/enhanced-rich-text-editor#14]
If used in the "normal" RichTextEditor" setMaxHeight can be used to limit the space of the editor content. If there are more lines than fit in the editor a scrollbar appears and the content can be scrolled.

This does not work in the Enhanced RTE. Instead the Toolbar disappears and never comes back on scrolling backwards.

**Comment by TatuLund** [comment]
For me it looks like the culprit is this one https://github.com/vaadin-component-factory/vcf-enhanced-rich-text-editor/blob/polymer-3/src/vcf-enhanced-rich-text-editor.js#L152
